### ISSUE TITLE
Add TLDR command

### ISSUE THREAD

**Issue by Kourior** [ZaneyPoo/QuadBot#1]
#### Idea:
When a user issues the TLDR command, reply with a short summary of the given message. 

#### Possible solution:
Use OpenAI API, preferably GPT 3 to minimize costs. This could go into a separate cog which would setup infrastructure for potential future LLM commands.

Due to cost, it would be important to put in place limits on the number of tokens per message and messages per day.

#### Tasks
- [ ] Add [OpenAI API](https://github.com/openai/openai-python) dependency to project.
- [ ] Setup QuadAI cog to manage connection and handle interacting with OpenAI API.
- [ ] Implement functions to check for rate limits before sending requests.
- [ ] Setup command function.
