### ISSUE TITLE
Add cowsay command

### ISSUE THREAD

**Issue by ZaneyPoo** [ZaneyPoo/QuadBot#18]
### Description
Cowsay is a timeless CLI classic. It's absence on Discord is dismaying to say the least... We could fix that by adding a command to invoke cowsay and pipe the output as a message. For simplicity's sake, we'd only care about the basic invocation and not any of the other cows (which is for the best frankly 😨).

**Example command**:
?cowsay "message" 
/cowsay "message

### Possible Solution
Cowsay is just a simple Perl script that places some text into an ascii drawing. By far the easiest solution is to just do this same formatting inside Python natively using fstrings or "{}" style string formatting. Invoking the original Perl script brings about a bunch of additional headaches (adding Perl and Cowsay as a dependency, calling an external process and piping the output into a message, etc). 

By far the biggest challenge of the reimplementing approach will be having to read the Cowsay's god-awful Perl script.

### Tasks
- [ ] Implement speech bubble word wrapping and formatting
- [ ] Implement cow construction
- [ ] Implement message command and slash command
- [ ] Tell Rickie about new QuadBot feature
