### ISSUE TITLE
Add command to create GitHub issues

### ISSUE THREAD

**Issue by ZaneyPoo** [ZaneyPoo/QuadBot#6]
### Idea:
Add a user command which can create issues on this GitHub repo automatically using user provided messages.
I think ideally, this would be primarily a slash command to better integrate with the more user-friendly GUI components that Discord offers. 
![image](https://github.com/Kourior/qbot/assets/144561696/815b4ecd-283b-440b-be17-629f974e6727)

### Possible Solutions:
From a brief initial search, I've found this library which could be used to add this functionality: [PyGithub](https://github.com/PyGithub/PyGithub)
Similar to the ideas related to interacting with the OpenAI API #1 , this would best be played into a new Cog (QuadGit?) so that more related commands could be added down the line.

### Tasks:
- [ ] Add PyGithub dependency to project.
- [ ] Setup QuadGit cog.
- [ ] Add issue slash command.
